
with open('game_data.py', 'a', encoding='utf-8') as f:
    f.write('\n\n# ============================================================\n')
    f.write('# PROGRESSION UNLOCKS\n')
    f.write('# ============================================================\n')
    f.write('FEATURE_UNLOCKS = {\n')
    f.write('    "esports": {"year": 2005, "name": "E-Sports"},\n')
    f.write('    "ipo": {"year": 1995, "office_level": 3, "name": "Boersengang (IPO)"},\n')
    f.write('    "darknet": {"year": 2000, "name": "Cyber-Attacken / Darknet"},\n')
    f.write('    "cloud_gaming": {"year": 2010, "name": "Cloud Gaming"},\n')
    f.write('    "merch": {"year": 1990, "name": "Merchandising"},\n')
    f.write('    "ai_tools": {"year": 2020, "name": "KI-Tools"},\n')
    f.write('    "streaming_platform": {"year": 2005, "name": "Streaming-Plattform"},\n')
    f.write('    "creator_sponsorship": {"year": 2010, "name": "Content Creators Sponsern"},\n')
    f.write('    "acquisition": {"year": 2000, "office_level": 3, "name": "Studio-Akquise"},\n')
    f.write('    "soundcon": {"year": 1995, "name": "SoundCon Messe"},\n')
    f.write('    "soundtrack_label": {"year": 1985, "name": "Soundtrack-Label"},\n')
    f.write('    "subscription_vault": {"year": 1995, "name": "Abo-Modell"}\n')
    f.write('}\n')
