import sys
import os
import re
import json

# Adding paths to import translations
sys.path.append(".")
from translations import TRANSLATIONS

# Manual translations for the missing English keys
EN_TRANSLATIONS_PATCH = {
    "bundle_create_btn": "Publish Bundle",
    "bundle_create_confirm": "Create bundle with selected games",
    "bundle_created": "Bundle '{name}' published! Sales: {sales:,}. Revenue: {rev:,} Euro.",
    "bundle_games_selected": "{count} games selected.",
    "bundle_max_reached": "Maximum of 3 games per bundle possible!",
    "bundle_menu": "Bundle Menu",
    "bundle_name_prompt": "What should the bundle be called?",
    "bundle_name_title": "Bundle Name",
    "bundle_no_games": "Not enough games available for a bundle.",
    "bundle_title": "Create Game Bundle",
    "buy_license_prompt": "Do you want to buy the {name} for {cost:,} Euro?",
    "by_label": "by",
    "calendar_week": "Calendar Week",
    "cancel": "Cancel",
    "candidates": "Candidates",
    "cell_occupied": "This space is already occupied!",
    "channel_beta_warning": "Beta channel activated! Beta versions may contain bugs.",
    "channel_stable_info": "Stable channel activated. Only tested versions will be installed.",
    "chart_entry": "#{rank}: {name} ({studio}) - {sales:,} sales",
    "chart_no_data": "No sales data available yet.",
    "chart_option": "Market Analysis",
    "chart_player_share": "Your Market Share: {share}%",
    "chart_title": "Sales Charts",
    "charts_empty": "No sales data available yet.",
    "charts_title": "Sales Charts",
    "check_update": "Check for updates",
    "checking_update": "Checking for updates, please wait...",
    "choose_genre_for_topic": "Choose a genre for your {topic} game.",
    "co_dev_no_partners": "No partners available.",
    "co_dev_partner_option": "{name} (Good tech, 50% profit share)",
    "co_dev_started": "Co-development with {name} started.",
    "coffee_machine": "Coffee Machine",
    "company_creation_title": "Company Founding",
    "company_name_prompt": "What should your game company be called?",
    "company_name_title": "Studio Founding",
    "company_overview": "Company Overview",
    "completed_label": "Completed",
    "confirm": "Confirm",
    "confirmed": "Confirmed: {text}",
    "console_specs": "Hardware Specifications",
    "continue_btn": "Continue",
    "create_console": "Design New Console",
    "create_console_title": "Design New Console",
    "create_engine": "Create New Engine",
    "create_engine_option": "Create New Engine",
    "create_engine_title": "Develop New Engine",
    "credits_text": "Music and sound effects were provided by Eric Matyas, www.soundimage.org.",
    "crunch_active": "[CRUNCH ACTIVE]",
    "crunch_info": "Crunch: Development 2x faster, but morale drops and bugs increase!",
    "crunch_off": "[CRUNCH OFF]",
    "current_balance": "Current Balance",
    "current_menu": "Current Menu",
    "current_project_short": "Current Project",
    "decline_poach": "Decline poaching offer",
    "decline_raise": "Decline request",
    "delete": "Delete",
    "delete_char": "{char} deleted. Current: {text}",
    "delete_email": "Delete Email",
    "desk": "Desk",
    "dev_audience_selected": "Target Audience: {audience}.",
    "dev_completed": "Development completed! Press Enter for reviews.",
    "dev_event_dev_crunch_offer_desc": "The team offers overtime. Accept?",
    "dev_event_dev_crunch_offer_title": "Overtime Offer",
    "dev_event_dev_data_loss_desc": "A server crash destroyed parts of the code! Restore backup or rewrite?",
    "dev_event_dev_data_loss_title": "Data Loss!",
    "dev_event_dev_key_employee_sick_desc": "Your key developer is sick! The project is at risk of falling behind.",
    "dev_event_dev_key_employee_sick_title": "Sick!",
    "dev_event_dev_positive_review_desc": "A journalist discovered your project. Release demo?",
    "dev_event_dev_positive_review_title": "Positive Hype!",
    "dev_event_dev_rival_copy_desc": "A competitor stole your concept! Develop faster or ignore?",
    "dev_event_dev_rival_copy_title": "Competitor Copied!",
    "dev_event_dev_scope_creep_desc": "Fans demand a new feature. Build it or stay focused?",
    "dev_event_dev_scope_creep_title": "Feature Request",
    "dev_event_dev_tech_breakthrough_desc": "Your team has an innovative idea! Do you want to build it in now?",
    "dev_event_dev_tech_breakthrough_title": "Technical Breakthrough!",
    "dev_event_dev_viral_moment_desc": "A video of your game went viral! Use the hype or stay calm?",
    "dev_event_dev_viral_moment_title": "Went Viral!",
    "dev_event_opt_dev_crunch_offer_accept_crunch": "Accept overtime",
    "dev_event_opt_dev_crunch_offer_decline_crunch": "Decline",
    "dev_event_opt_dev_data_loss_restore_backup": "Restore backup",
    "dev_event_opt_dev_data_loss_rewrite": "Rewrite",
    "dev_event_opt_dev_key_employee_sick_continue_without": "Continue without them",
    "dev_event_opt_dev_key_employee_sick_hire_freelancer": "Hire freelancer",
    "dev_event_opt_dev_positive_review_keep_secret": "Keep secret",
    "dev_event_opt_dev_positive_review_release_demo": "Release demo",
    "dev_event_opt_dev_rival_copy_ignore_rival": "Ignore competitor",
    "dev_event_opt_dev_rival_copy_speed_up": "Accelerate development",
    "dev_event_opt_dev_scope_creep_add_feature": "Add feature",
    "dev_event_opt_dev_scope_creep_stay_focused": "Stay focused",
    "dev_event_opt_dev_tech_breakthrough_implement_now": "Build in now",
    "dev_event_opt_dev_tech_breakthrough_save_for_sequel": "Save for sequel",
    "dev_event_opt_dev_viral_moment_embrace_hype": "Embrace hype",
    "dev_event_opt_dev_viral_moment_focus_quality": "Prioritize quality",
    "dev_event_opt_finish": "Finish CGI trailer",
    "dev_event_opt_focus": "Stay focused",
    "dev_event_opt_hire": "Hire celebrity voice",
    "dev_event_opt_ignore": "Ignore leak",
    "dev_event_opt_implement": "Add feature",
    "dev_event_opt_pass": "Skip",
    "dev_finish_prompt": "Development completed! Publish or Polishing?",
    "dev_finished_prompt": "Development completed! Publish or Polishing?",
    "dev_genre_selected": "{topic} plus {genre}: {compat_text}.",
    "dev_marketing_error": "Not enough money. You need {cost:,} Euro.",
    "dev_marketing_success": "Marketing booked. Hype increased by {hype}. Current hype: {current_hype:.1f}.",
    "dev_name_prompt": "Enter game name. Your {topic} {genre} game on {platform}. Type the name and press Enter.",
    "dev_name_success": "Game name: {name}. Proceed to development!",
    "dev_not_finished": "Development has not progressed far enough yet!",
    "dev_percent": "{percent} percent finished. {bugs} bugs. Hype: {hype:.1f}.",
    "dev_platform_license_error": "Not enough money for the {platform} license. You need {cost:,} {currency}.",
    "dev_platform_selected": "Platform: {platform}.",
    "dev_polish_start": "Polishing active. Press arrow key or Enter to open the menu again at any time.",
    "dev_polish_update": "Polishing: {bugs} bugs left.",
    "dev_progress": "Game Development",
    "dev_progress_menu": "Development Status",
    "dev_progress_start_info": "Development of {name} started. Duration: {weeks} weeks. Use 1, 2, 3 for speed and C for Crunch.",
    "dev_progress_update": "{percent} percent finished. {bugs} bugs. Hype: {hype:.1f}.",
    "dev_remaster_selected": "Classic {game} selected. Directly to platform choice.",
    "dev_result_money": "New balance: {money:,} Euro. Fans: {fans:,}.",
    "dev_result_sales": "Sales: {sales:,} units. Revenue: {revenue:,} Euro. Costs: {cost:,} Euro. Profit: {profit:,} Euro.",
    "dev_review_avg": "Average rating: {avg:.1f} out of 10.",
    "dev_review_intro": "The reviews for '{game}' are in!",
    "dev_review_sales": "Sales: {sales:,} units. Revenue: {rev:,} Euro. Costs: {cost:,} Euro. Profit: {profit:,} Euro.",
    "dev_review_saved": "Game state saved. Goodbye!",
    "dev_review_score": "Reviewer {num}: {score} out of 10.",
    "dev_review_wallet": "New balance: {money:,} Euro. Fans: {fans:,}.",
    "dev_select_genre_speak": "Choose a genre for your {topic} game.",
    "dev_select_topic_speak": "Choose a topic for your game.",
    "dev_size_employee_error": "For a {size} game you need at least {min_emp} employees. You only have {current_emp}.",
    "dev_size_selected": "Size: {size}.",
    "dev_slider_explain": "Development of '{name}', a {topic} {genre} game on {platform}. Estimated cost: {cost:,} Euro. Distribute {budget} points to 6 areas.",
    "dev_slider_prompt": "Development of '{name}', a {topic} {genre} game on {platform}. Estimated cost: {cost:,} Euro. Distribute {budget} points to 6 areas.",
    "dev_sliders_title": "Slider Distribution",
    "dev_engine_selected": "Engine: {engine}, Tech-Level {tech}.",
    "dev_event_": "",
    "dev_event_opt_": "",
    "production_menu_title": "Production & Storage Management",
    "story_Krieg": "Experience intense battlefields and strategic maneuvers in a fierce war.",
    "story_Mittelalter": "Fight for dominance in a harsh world full of knights and castles.",
    "story_Musik": "Follow the rhythm and rise to become a celebrated music legend.",
    "story_Piraten": "Set sail and conquer the seven seas in the hunt for treasures.",
    "story_Polizei": "Ensure law and order on the streets of a crime-ridden city.",
    "story_Rennen": "Step on the gas and win in fast-paced races against challenging opponents.",
    "story_Schule": "Master everyday school life between exams, friendships, and drama.",
    "story_Sci-Fi": "A gripping journey through futuristic worlds and high-tech conflicts.",
    "story_Spionage": "Sneak unnoticed into enemy bases and collect secret information.",
    "story_Sport": "Experience exciting competitions and lead your team to the top of the league.",
    "story_Stadt": "Build and manage a thriving metropolis according to your own ideas.",
    "story_Superheld": "Use your superpowers to protect innocent citizens from supervillains.",
    "story_Tiere": "Take care of lovable animals and create a paradise for them.",
    "story_Vampire": "Explore the dark secrets of the night and the intrigues of the bloodsuckers.",
    "story_Weltraum": "Explore endless galaxies and discover new civilizations among the stars.",
    "story_Wilder Westen": "Explore the harsh frontier era full of bandits, saloons, and exciting duels.",
    "story_Zombies": "Survive in a post-apocalyptic world overrun by the undead.",
    "sub_genre_none": "No sub-genre",
    "sub_genre_selected": "Sub-genre: {name}",
    "sub_genre_title": "Select Sub-Genre",
    "subgenre_title": "Sub-genre choice",
    "subject_achievement": "🏆 MILESTONE REACHED: {title}",
    "subject_bug_report": "Complaint about {game}",
    "subject_co_dev": "Co-development settlement: {name}",
    "subject_console_dead": "Production discontinued: {name}",
    "subject_console_done": "Console completed!",
    "subject_dividend": "Dividend received!",
    "subject_employee_left": "Resignation: {name}",
    "subject_expo": "Audio Expo coming up!",
    "subject_fan_praise": "I love {game}!",
    "subject_goty": "GOTY Committee",
    "subject_goty_lose": "GOTY {year} goes to {name}!",
    "subject_goty_win": "GAME OF THE YEAR AWARD!",
    "subject_historical_event": "{year}: Current Event",
    "subject_intel_report": "Spy Report: {name}",
    "subject_license_expired": "License expired",
    "subject_loan_paid": "Loan repaid",
    "subject_merch_sold_out": "Merch sold out!",
    "subject_monthly_statement": "Your bank statement - {date}",
    "subject_new_console": "New console: {name}",
    "subject_new_month": "New month: {date}",
    "subject_new_topic": "A new era begins!",
    "subject_new_topics_year": "{year}: New topics available!",
    "subject_pioneer_times": "Welcome to the pioneer era!",
    "subject_poach_offer": "Contract offer for {name}",
    "subject_quit": "Resignation",
    "subject_research_done": "Research completed!",
    "subject_rival_hit": "Mega hit by {name}!",
    "subject_salary_raise": "Salary negotiation",
    "subject_server_overload": "SERVER OVERLOADED",
    "subject_sick": "Sick leave: {name}",
    "subject_sick_recovered": "Recovery: {name}",
    "subject_studio_income": "Income Report",
    "subject_training_done": "Training completed: {name}",
    "subject_yearly_report": "Yearly balance {year}",
    "subscription_change_price": "Change price",
    "subscription_info": "Info: {subs:,} subscribers generate monthly income, but also server costs. Hype keeps subscribers.",
    "subscription_library_size": "Games in the library: {count}",
    "subscription_manage_library": "Manage library",
    "subscription_menu_title": "Subscription Service (Game Pass)",
    "subscription_price_down": "Lower monthly price (Current: {price} EUR)",
    "subscription_price_label": "Monthly price: {price} EUR",
    "subscription_price_up": "Raise monthly price (Current: {price} EUR)",
    "subscription_server_costs_label": "Server costs: {cost:,} EUR / week",
    "subscription_start": "Start subscription service",
    "subscription_status_active": "Active",
    "subscription_status_inactive": "Inactive",
    "subscription_stop": "Stop subscription service",
    "subscription_subscribers_label": "Subscribers: {count:,}",
    "subscription_trend_label": "Trend: {trend}",
    "support_dev": "Support developer (GitHub)",
    "support_gift_card": "Send gift card code (Google Play, Steam, Paysafe)",
    "support_gift_card_desc": "Thank you for your support! You can send me Google Play, Steam, or Paysafecard codes.",
    "support_gift_card_mail_body": "Hello! I want to support you. Here is a {type} code: {code}",
    "support_gift_card_mail_subject": "Gift card code for Audio Studio Tycoon",
    "support_gift_card_prompt": "Enter the code here. After that, your email program will open.",
    "support_gift_card_thanks": "Thank you! The code has been recorded. Please send the email that will open shortly.",
    "support_gift_card_title": "Gift Card Support",
    "support_gift_card_type_select": "Select the type of gift card:",
    "take_loan_option": "Take out a loan",
    "team_confirm": "Confirm selection ({count} employees)",
    "team_member_status": "{name} ({role}) - {status}",
    "team_none_selected_error": "You must assign at least one employee!",
    "team_select_prompt": "Choose who should work on this project. Enter to toggle. Last option to confirm.",
    "team_status_assigned": "Assigned",
    "team_status_not_assigned": "Not assigned",
    "teambuilding_party": "Office Party (2,000 EUR)",
    "teambuilding_pizza": "Pizza Night (500 EUR)",
    "teambuilding_success": "{type} was a complete success!",
    "teambuilding_trip": "Team Trip (5,000 EUR)",
    "team_building_title": "Team Building",
    "tech_level_label": "Tech Level",
    "time_speed_speech": "Time speed: {speed}",
    "topic_menu": "Topic Choice",
    "train_choose": "Choose training for {name}.",
    "train_employee": "Train employee",
    "train_option_desc": "{name} - {desc} (Cost: {cost:,} Euro)",
    "train_select": "Choose an employee to train.",
    "train_success": "Training successful! {name} has improved. New salary: {salary} Euro. Remaining money: {money:,} Euro.",
    "training_already_in": "{name} is already in training and cannot be registered again!",
    "training_employee": "Choose employee for training",
    "training_error": "An error occurred. Training could not be started.",
    "training_option": "Choose training program",
    "training_option_desc": "{cost:,} EUR — +{boost} skill points — {weeks} week(s) absence",
    "training_option_spec_desc": "{cost:,} EUR — New specialization — {weeks} weeks absence",
    "training_sick_blocked": "Sick employees cannot start training. Please wait for recovery first.",
    "training_started": "{name} is now in {opt}. Returning in {weeks} week(s).",
    "training_started_spec": "{name} is completing the specialization course and returns as '{spec}'! Duration: {weeks} weeks.",
    "training_status_tag": "In training ({weeks} weeks remaining)",
    "training_success": "Training successful! {name} has improved.",
    "trend": "TREND",
    "tts_auto": "Automatic TTS",
    "tts_mode": "Speech / TTS Mode",
    "typing_prompt": "Type the name and press Enter.",
    "unselected": "unselected",
    "update_available": "Update available! Version {version}. Download and install? (Caution: Game will restart)",
    "update_error": "Error searching for updates.",
    "update_options": "Update Options",
    "upgrade_bought": "{name} was purchased and installed in the office!",
    "upgrade_chairs": "Ergonomic Chairs",
    "upgrade_coffee": "Coffee Machine",
    "upgrade_intel": "Market Research Subscription",
    "upgrade_legal": "Law Firm Retainer",
    "upgrade_morale_room": "Break room with table football",
    "upgrade_office": "Upgrade Office",
    "upgrade_pr": "PR Agency Retainer",
    "upgrade_security": "Security Service",
    "volume_music": "Music Volume",
    "volume_settings": "Volume Settings",
    "volume_sfx": "SFX Volume",
    "volume_speech": "Speech Volume",
    "wall": "Wall",
    "watch_ad": "Watch ad video (+5,000 EUR)",
    "week": "Week",
    "weeks": "Weeks",
    "welcome_body": "The year is 1930. You are a visionary with a big idea: you can teach machines to play and develop games! With modest means in a garage, you start your studio. Available topics: Abacus, Mathematics, Chess, and Logistics. Fight your way through history – from the Great Depression to the AI revolution of 2023!",
    "welcome_company": "Welcome to {name}! You have {money:,} Euro starting capital. You start in a garage. Time to develop your first game!",
    "welcome_sender": "Historian",
    "welcome_subject": "Welcome to the pioneer era!",
    "wiki": "Wiki / Help",
    "wiki_chapter_controls": "Chapter 1: Controls & Basics",
    "wiki_chapter_dev": "Chapter 3: Game Development & Sliders",
    "wiki_chapter_gameplay": "Chapter 2: Game Goal & Finances",
    "wiki_chapter_hr": "Chapter 4: Personnel & Training",
    "wiki_chapter_mods": "Chapter 7: Creating and Activating Mods",
    "wiki_chapter_money": "Chapter 6: Bank, Stock Market & Licenses",
    "wiki_chapter_research": "Chapter 5: Research & Engines",
    "wiki_chapter_tutorial": "Chapter 0: Introduction for Beginners",
    "wiki_concept": "Concept: Choose topic and genre appropriately.",
    "wiki_controls_text": "CONTROLS: Arrow up and arrow down navigate options. Enter confirms. Backspace goes back. Home jumps to the beginning of a list. End jumps to the end. Spacebar or 0 pauses time. 1 sets normal speed. 2 sets fast speed. 3 sets ultra-fast. The C key activates or deactivates crunch mode during development.",
    "wiki_dev": "Development: Pay attention to the slider distribution!",
    "wiki_dev_text": "GAME DEVELOPMENT: Start with topic, genre, platform, target audience, size, and marketing. Then distribute points across 6 sliders: Gameplay, Graphics, Sound, Story, AI, and World. Every genre has an ideal slider distribution. An action game needs a lot of gameplay and little story. An RPG needs a lot of story and world. The better you hit the distribution, the higher the rating. Use crunch only in emergencies: it speeds up development, but bugs increase and morale drops.",
    "wiki_gameplay_text": "GAME GOAL: Found a game developer studio and become the largest publisher in the world! Choose topics and genres carefully, as some combinations do not fit well together. Watch the market trend: if a certain topic is trending, a matching game sells much better. Keep an eye on your expenses. Employee salaries, office rent, and research costs run every week. If you run out of money, you lose the game.",
    "wiki_hr": "Personnel: Specialists give strong bonuses.",
    "wiki_hr_text": "PERSONNEL: Hire employees to develop larger games. Every employee has a main role (Programmer, Graphic Artist, Sound Designer, Supporter) and gives a bonus to their area. Specializations like Sound Genius or Bug Hunter give additional bonuses. Train employees regularly so their level rises. Pay attention to morale: if it drops below 30 percent, the team works slowly and produces more bugs. Team-building measures (pizza, party, trip) help.",
    "wiki_mods_text": "CREATING MODS: The game supports local mods without internet! This is how you create a mod: Step 1: Open the mods folder in the game directory. Step 2: Create a new subfolder in it, for example my_mod. Step 3: Create a file called mod.json in this folder. Step 4: Fill the file with the following content: curly brace open. id: unique ID in quotes (e.g. my_mod). name: Name of the mod in quotes. author: your name in quotes. version: e.g. 1.0. description: short description. add underscore topics: square bracket open. curly brace open name: 'Your topic', trend underscore text: 'Your topic is booming right now!' curly brace close. square bracket close. add underscore genres: analog. curly brace close. Step 5: Start the game, go to Local Mod Manager and activate the mod with Enter. From the next game start, the new topics and genres are available!",
    "wiki_money_text": "MONEY & FINANCES: Only take out loans if you can safely repay them. The loan is automatically repaid every week. On the stock market, you can buy shares in competing studios and benefit from dividends. Licenses (movies, anime, sports leagues) give hype bonuses to your next game. Bundles and add-ons are cheap ways to generate additional income from finished games.",
    "wiki_research_text": "RESEARCH: Research new topics, genres, target audiences, and engine features. Then create your own engines from the researched features. The higher the tech level of your engine, the better the ratings of your games. For large and AAA games, you need special technologies like digital distribution or hardware lab. Always keep at least one engine with current tech level ready.",
    "wiki_tutorial_text": "STEP-BY-STEP GUIDE: 1. Select 'Develop New Game'. 2. Choose a topic and genre (e.g. Fantasy and RPG). 3. Select a platform and target audience. 4. Distribute the sliders appropriately for the genre (Tip: Action needs a lot of gameplay, RPG a lot of story). 5. Confirm with Enter and wait for development. 6. Publish the game. 7. Use the profit for research or new personnel. IMPORTANT: Press 'S' for a status overview (money, date, research) and 'F' for your finances at any time in the game. Skill points improve the quality of your games and increase through training or experience.",
    "wiki_welcome": "Welcome to the Wiki. Choose a topic.",
    "wiki_welcome_new": "Welcome to the Wiki & Help system! Choose a chapter with the arrow keys and press Enter to have it read aloud.",
    "year_label": "Year",
    "year_report_rival_score": "- {name}: average rating {score}/10",
    "year_report_rivals": "Competitor report for the year {year}:",
    "yearly_best_game": "Top seller of the year",
    "yearly_report_title": "Financial report for the year {year}",
    "yes_update": "Yes, install update"
}

DE_TRANSLATIONS_PATCH = {
    "production_merge_title": "Produktion & Lagerverwaltung",
    "story_Krankenhaus_desc": "Rette Leben und manage den stressigen Alltag einer Klinik.",
    "team_building_title": "Teambuilding"
}

def apply_patches():
    # Update German
    TRANSLATIONS['de'].update(DE_TRANSLATIONS_PATCH)
    
    # Update English
    TRANSLATIONS['en'].update(EN_TRANSLATIONS_PATCH)
    
    # Sort dictionaries by key for cleanliness
    TRANSLATIONS['de'] = dict(sorted(TRANSLATIONS['de'].items()))
    TRANSLATIONS['en'] = dict(sorted(TRANSLATIONS['en'].items()))
    
    # Template for translations.py
    header = '"""\nTranslations for Audio Studio Tycoon.\nOnly German is stored, other languages are translated on-the-fly.\n"""\nimport sys\nimport os\nimport json\nimport urllib.request\nimport urllib.parse\nimport re\nimport threading\n\nCACHE_FILE = "translation_cache.json"\n_TRANSLATION_CACHE = {}\nTRANSLATIONS_UPDATED = False\nPENDING_TRANSLATIONS = 0\nCACHE_LOCK = threading.Lock()\n\nif os.path.exists(CACHE_FILE):\n    try:\n        with open(CACHE_FILE, "r", encoding="utf-8") as cf:\n            _TRANSLATION_CACHE = json.load(cf)\n    except:\n        pass\n\ndef save_cache():\n    try:\n        with CACHE_LOCK:\n            with open(CACHE_FILE, "w", encoding="utf-8") as cf:\n                json.dump(_TRANSLATION_CACHE, cf, ensure_ascii=False, indent=2)\n    except:\n        pass\n\ndef background_translate(text, target_lang, cache_key, source_lang="de"):\n    global PENDING_TRANSLATIONS, TRANSLATIONS_UPDATED\n    try:\n        placeholders = {}\n        def replacer(match):\n            ph = match.group(1)\n            token = f"__PH_{len(placeholders)}__"\n            placeholders[token] = ph\n            return token\n        protected_text = re.sub(r"\\{([^}]+)\\}", replacer, text)\n        encoded_text = urllib.parse.quote(protected_text)\n        url = f"https://translate.googleapis.com/translate_a/single?client=gtx&sl={source_lang}&tl={target_lang}&dt=t&q={encoded_text}"\n        \n        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})\n        with urllib.request.urlopen(req, timeout=5) as response:\n            result = json.loads(response.read().decode("utf-8"))\n            translated = "".join([sentence[0] for sentence in result[0]])\n            for token, ph in placeholders.items():\n                token_pattern = re.compile(token.replace("_", r"_?\\s*"))\n                translated = token_pattern.sub(f"{{{ph}}}", translated)\n            \n            with CACHE_LOCK:\n                _TRANSLATION_CACHE[cache_key] = translated\n            save_cache()\n            \n            TRANSLATIONS_UPDATED = True\n    except Exception as e:\n        pass\n    finally:\n        PENDING_TRANSLATIONS -= 1\n\ndef get_system_language():\n    try:\n        if sys.platform == "win32":\n            import ctypes\n            windll = ctypes.windll.kernel32\n            lang_id = windll.GetUserDefaultUILanguage()\n            primary_lang = lang_id & 0x3ff\n            if primary_lang == 0x07:\n                return "de"\n        return "en"\n    except:\n        return "en"\n\nCURRENT_LANGUAGE = get_system_language()\n\ndef set_language(lang):\n    global CURRENT_LANGUAGE\n    CURRENT_LANGUAGE = lang\n\ndef get_text(text_key, **kwargs):\n    """\n    Retrieves the translated text for a given key.\n    Prioritizes: CURRENT_LANGUAGE -> English (en) -> German (de) -> Key itself.\n    """\n    # 1. Try current language static translation\n    text = TRANSLATIONS.get(CURRENT_LANGUAGE, {}).get(text_key)\n    \n    # 2. If not found and not in English, try English static translation\n    if text is None and CURRENT_LANGUAGE != "en":\n        text = TRANSLATIONS.get("en", {}).get(text_key)\n        \n    # 3. If still not found and not in German, try German static translation\n    if text is None and CURRENT_LANGUAGE != "de":\n        text = TRANSLATIONS.get("de", {}).get(text_key)\n        \n    # 4. If still not found, use the key itself as a base\n    if text is None:\n        text = text_key\n\n    if kwargs:\n        try:\n            return text.format(**kwargs)\n        except:\n            return text\n    return text\n\n'
    
    # Ensure json is imported before dump
    content = header + "TRANSLATIONS = " + json.dumps(TRANSLATIONS, indent=4, ensure_ascii=False) + "\n"
    
    with open("translations.py", "w", encoding="utf-8") as f:
        f.write(content)
    
    print("translations.py updated successfully!")

if __name__ == "__main__":
    apply_patches()
